name: Builds, tests & co

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@6feb50d340ce0fb56d35cefca7ae674c70cfd986 # v3.5.0
        with:
          ocaml-compiler: 4
      - name: Set-up Mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1.6.4.0.1
        with:
          cache: false
      - name: Load environment variables
        run: |
          direnv allow .
          direnv export gha >"$GITHUB_ENV"
      - run: yarn install --immutable
      - run: opam install . --deps-only
      - run: make
      - run: node dist/main.bc.js

  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@6feb50d340ce0fb56d35cefca7ae674c70cfd986 # v3.5.0
        with:
          ocaml-compiler: 4
      - uses: ocaml/setup-ocaml/lint-fmt@6feb50d340ce0fb56d35cefca7ae674c70cfd986 # v3.5.0

  lint-opam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@6feb50d340ce0fb56d35cefca7ae674c70cfd986 # v3.5.0
        with:
          ocaml-compiler: 4
      - uses: ocaml/setup-ocaml/lint-opam@6feb50d340ce0fb56d35cefca7ae674c70cfd986 # v3.5.0
